### ISSUE TITLE
How to create mask for 1st frame?

### ISSUE THREAD

**Issue by yousaf446** [z-x-yang/CFBI#47]
I am trying to create my own dataset for inference. I created mask for first frame and then supply it with my own dataset but I am getting cuda out of memory error.

Traceback (most recent call last):
  File "tools/eval_net.py", line 72, in <module>
    main()
  File "tools/eval_net.py", line 69, in main
    evaluator.evaluating()
  File ".\networks\engine\eval_manager.py", line 181, in evaluating
    all_pred, current_embedding = self.model.forward_for_eval(ref_emb, ref_m, prev_emb, prev_m, current_img, gt_ids=obj_num, pred_size=[ori_height,ori_width])
  File ".\networks\cfbi\cfbi.py", line 93, in forward_for_eval
    tf_board=False)
  File ".\networks\cfbi\cfbi.py", line 186, in before_seghead_process
    use_float16=cfg.MODEL_FLOAT16_MATCHING)
  File ".\networks\layers\matching.py", line 325, in global_matching_for_eval
    reference_embeddings_flat, query_embeddings_flat, reference_labels_flat, n_chunks)
  File ".\networks\layers\matching.py", line 125, in _nearest_neighbor_features_per_object_in_chunks
    wrong_label_mask)
  File ".\networks\layers\matching.py", line 81, in _nn_features_per_object_for_chunk
    WRONG_LABEL_PADDING_DISTANCE)
RuntimeError: CUDA out of memory. Tried to allocate 26.97 GiB (GPU 0; 11.00 GiB total capacity; 558.30 MiB already allocated; 8.43 GiB free; 594.00 MiB reserved in total by PyTorch)

Can you please let me know how I can create mask for first frame? I also attached mask file.
![00000](https://user-images.githubusercontent.com/9824740/129188996-b096d2d8-9ec3-46f0-9414-13fa3fe75884.png)

**Comment by z-x-yang** [comment]
Please refer to this [issue](https://github.com/z-x-yang/CFBI/issues/23#issue-790617837).

**Comment by yousaf446** [comment]
Do you have any sample code inside this repository for creating these masks?

**Comment by z-x-yang** [comment]
No. These masks are always annotated by some annotation tools. Just like annotating semantic segmentation.

**Comment by yousaf446** [comment]
Is their any specific tool available in which I can get masks in this format? I tried coco annotator but it didn't give output in this format.

**Comment by z-x-yang** [comment]
You could use PIL library to attach a palette to a gray scale image like [this](https://github.com/z-x-yang/CFBI/blob/f4479afa07d68fa87aac790f2c1a817fc78d6b02/utils/image.py#L31).

**Comment by z-x-yang** [comment]
However, the palette is useless for inference but only useful for visualization.

**Comment by yousaf446** [comment]
> You could use PIL library to attach a palette to a gray scale image like [this](https://github.com/z-x-yang/CFBI/blob/f4479afa07d68fa87aac790f2c1a817fc78d6b02/utils/image.py#L31).

Thanks it worked
